name: config
api:
  Seckey: 

  Github_api_token: 
  Censys_api_id: 
  Censys_api_secret: 

  Shodan_key: 

  Virustotal_key: 

  Zoomeye_username: 
  Zoomeye_password: 

  Spyse_token: 

  Fofa_Cookie: 

  Google_key: 
  Google_cx: 

gmail:
  ServerHost: 
  ServerPort: 
  FromEmail: 
  FromPasswd: 
  Toers: 

mysql:
  SqlUserName: "root"
  SqlPassWord: "root"
  Host: "127.0.0.1:3306"

proxy: http://127.0.0.1:1080/
